<?php

declare(strict_types=1);

require_once __DIR__ . '/../QueueController.php';

/**
 * Backward-compatible admin controller for URLs generated by the initial 2.x
 * admin menu path: adminhtml/hirale_queue.
 */
class Hirale_Queue_Adminhtml_Hirale_QueueController extends Hirale_Queue_Adminhtml_QueueController
{
}
